### ISSUE TITLE
[ISSUE-77] 방 등록시 유효조건 수정 /  방 정보 뿌릴 때 조건 체크

### ISSUE THREAD

**Issue by seokju2ng** [inezzz/murmul-er#164]
![image](https://user-images.githubusercontent.com/43347250/63350902-3a7a0a80-c399-11e9-945f-4e562163dd67.png)

1. 방 등록시
1.1. 전세 체크하면 월세 disabled
1.2. 월세 체크하면 보증금/월세 둘다 입력받아야하게 (현행 유지)

2. 방 정보 뿌릴때(마커위overlay, 지도 우측 리스트, 방관리, 관심목록 등등)
2.1. 전세일 경우 보증금만 출력
2.2. 월세일 경우 보증금, 월세 같이 출력
2.3. 억단위 변환 잘되는지 체크

**Comment by tjdwls3469** [comment]
1. 방 등록시 (완료)
   1.1. 전세 체크하면 월세 disabled (완료)
   1.2. 월세 체크하면 보증금/월세 둘다 입력받아야하게 (현행 유지) (완료)

**Comment by xyzzeong** [comment]
[ISSUE-95]에서 해결
2. 방 정보 뿌릴때(마커위overlay, 지도 우측 리스트, 방관리, 관심목록 등등) (완료)
2.1. 전세일 경우 보증금만 출력 (완료)
2.2. 월세일 경우 보증금, 월세 같이 출력 (완료)
2.3. 억단위 변환 잘되는지 체크 (완료)
