### ISSUE TITLE
[ISSUE-10] 방 등록 서비스 / 방 수정 서비스

### ISSUE THREAD

**Issue by seokju2ng** [inezzz/murmul-er#19]
- 방 수정 서비스 통합
- 방 등록 서비스를 방 수정 서비스와 폼맞추기
- 방 관리 서비스 완료

**Comment by enchanted13th** [comment]
스프링으로 전환한 부분 기록 남겨 놓는 건가요?

**Comment by seokju2ng** [comment]
방 수정이랑 등록 통합중입니다.

**Comment by kwongiho** [comment]
이슈에 labels같은걸 등록해놓으면 좋아요 

또한 작업을 진행할 사람은,
assignees을 자신으로 걸어두는것도 좋아요

**Comment by seokju2ng** [comment]
아하! 감사합니다

**Comment by lecto17** [comment]
감사합니다!

**Comment by lecto17** [comment]
- 방 수정 폼 수정(floor 추가)
