### ISSUE TITLE
[ISSUE-125] 내 방관리 버그 잡기

### ISSUE THREAD

**Issue by lecto17** [inezzz/murmul-er#285]
1. 방 관리에서 개발자도구에 버튼에 value 값 변경하여 다른 방 수정/삭제/변경 가능하다.

2. 수정 말고, 상세보기를 하고 싶을 때 내방을 바로 갈 수 있는 접근성이 떨어진다.

**Comment by tjdwls3469** [comment]
1. 완료
2. 나중에
