### ISSUE TITLE
[ISSUE-129] 마이페이지 버그 잡기

### ISSUE THREAD

**Issue by lecto17** [inezzz/murmul-er#289]
~~1. 개인정보 수정에서 연락처 공백으로 개인정보 수정하면 개인정보 수정 페이지 못 들어간다 (디비에는 공백으로 입력됨)~~

~~2. 개인정보 수정에서 아이디, 이름, 닉네임, 이메일, 휴대폰, 비밀번호 유효성 검사가 안된다.~~

~~3. 마이 페이지에서 전화번호를 특수 문자로 변경 후, 수정 성공 메시지가 뜨고 다시 재접속을 하면 404에러가 뜬다.~~

~~4. 최근 본 목록에 있는 매물들이 로그아웃시 사라지게 된다.~~

~~5. 마이페이지에서 내방으로 바로 가기가 불가능한게 불편하다.~~

**Comment by seokju2ng** [comment]
- 1, 2, 3번 해결
- 4, 5번은 의도
