### ISSUE TITLE
[ISSUE-20] Top Bar

### ISSUE THREAD

**Issue by xyzzeong** [inezzz/murmul-er#37]
- 로고에 li, button 사이즈 수정
- 버튼 마다 요청 url 수정

**Comment by seokju2ng** [comment]
- 로고 이미지 짤리던 증상 수정 OK (사파리 확인, **IE 확인 요망**)

**Comment by seokju2ng** [comment]
- IE 확인 결과, CSS의 calc()가 동작하지 않음.

**Comment by seokju2ng** [comment]
- topbar.css 에서 button 값 수정
  => background-color : transparent
