### ISSUE TITLE
[ISSUE-46] 관리자 페이지 / 신고된 방 관리

### ISSUE THREAD

**Issue by enchanted13th** [inezzz/murmul-er#98]
- 신고된 방 관리

**Comment by seokju2ng** [comment]
TO DO
- 신고 목록 보기
- 처리 상태 별로 뽑기(처리중, 처리완료 등)
- 처리 상태 변경하기(처리중, 처리완료 등)
- 신고된 방 상세정보 보기
- 방의 게시상태 변경하기(게시 금지 등)
